unclecode/crawl4ai

.gitignore
main.py

Origin: `zh-CN`. Requires `utf-8` to render a page
```markdown
File "T:\_GitHubProjects\Forks\crawl4ai\main.py", line 70, in read_index
partials[filename[:-5]] = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 149: illegal multibyte sequence
```
as below:
```diff
- with open(path, "r") as file:
+ with open(path, "r", encoding="utf8") as file:
```
I'm troubleshooting the same problem elsewhere.

fix(main): UnicodeDecodeError

---

setup.py

This PR addresses an installation error where a UnicodeDecodeError is raised when reading the README.md file. The error occurs because the default encoding is not always UTF-8, which causes issues when the file contains special characters.
Changes Made:
Modified the setup.py file to read README.md with UTF-8 encoding to ensure compatibility across different environments.
- Verified the installation process works correctly after making the change by testing it locally.
Linked Issue:
Fixes #36

Fix UnicodeDecodeError by reading README.md with UTF-8 encoding

---

README.md

This pull request updates the CSS selector in the Advanced Usage example in the README.md file. The change fixes a non-functioning example and ensures that the crawler can successfully extract content from the NBC News business page.
The previous selector `"article.tease-card"` was not functioning correctly and failed to extract any data from the NBC News business page. The new selector `.wide-tease-item__description` successfully targets the description text of the news articles, allowing the crawler to extract the intended content.
- Updated the `css_selector` parameter in the `crawler.arun()` method from `"article.tease-card"` to `".wide-tease-item__description"`.

docs: fixed css_selector for example

---

README.md

Hi, Crawl4AI team!
While I was browsing the README for instructions to install Crawl4AI, I discovered that some links are incorrect:
I fixed them on the README and also fix a few Markdown lint issues

chore(docs): fix documentation links + markdown lint fix

---

crawl4ai/async_webcrawler.py

This pull request includes a change to the `crawl4ai/async_webcrawler.py` file, specifically modifying the `aprocess_html` function to use the `pop` method for extracting keyword arguments instead of the `get` method.
Codebase simplification:
* [`crawl4ai/async_webcrawler.py`](diffhunk://#diff-4615044bdaa338cb6b9bbb86d0ae9831b2695d86d50e65995c43aa2dd49bfddaL200-R201): Changed the `aprocess_html` function to use `kwargs.pop` instead of `kwargs.get` for `only_text` and `image_description_min_word_threshold`. This ensures that these keyword arguments are removed from `kwargs` after being accessed to prevent pass duplicated kwargs to scrapping_strategy.

Fix #260 prevent pass duplicated kwargs to scrapping_strategy

---

crawl4ai/crawler_strategy.py

Bug Description：
The following code captures exceptions but is missing the variable e. If this exception occurs, the program will lack the variable e and will panic.
https://github.com/unclecode/crawl4ai/blob/38044d4afe16b48783457e5ec8538e0a7592e16b/crawl4ai/crawler_strategy.py#L286-L289

fix: crawler strategy exception handling and fixes

---

crawl4ai/async_crawler_strategy.py

Crawling webpage URLs (_https://www.metanous.be/_ in the example) sometimes raise the following error when using the default crawling strategy:
```
[INIT].... → Crawl4AI 0.3.744
[ERROR]... × https://www.metanous.be/... | Error: 
┌───────────────────────────────────────────────────────────────────────────────┐
│ × async_crawler_strategy.py:_crawleb(): Page.evaluate: Execution context was  │
│ destroyed, most likely because of a navigation                                │
└───────────────────────────────────────────────────────────────────────────────┘
```
I have tracked down the error and found that it is raised when executing the following line of code in the `async_crawler_strategy._crawl_web`-function:
https://github.com/unclecode/crawl4ai/blob/b0419edda6c0a25da82f65f557beee4e0a3daf02/cr …

AsyncPlaywrightCrawlerStrategy page-evaluate context destroyed by navigation

---

docs/md_v2/basic/quickstart.md

Import Statement Typo: CasheMode should be CacheMode. This typo will cause an import error.

Fix typo in import statement in quickstart.md

---

crawl4ai/async_configs.py

BREAKING CHANGE: Updated `chrome_channel` to **`chromium`** to fix compatibility with the new Chromium headless implementation. This resolves the error `playwright._impl._errors.Error: BrowserType.launch: Chromium distribution 'chrome' is not found`, caused by the removal of the old headless mode in Chromium.
With this change, channels like "chrome" now default to the new headless mode, aligning with upstream updates in Playwright v1.49.0 The new headless mode uses the real Chrome browser, offering more authenticity, reliability, and feature parity with the full browser.
Additionally, simplified fallback logic by directly assigning `chrome_channel` based on `browser_type` or defaulting to `chromium`.
Refer to:
- https://playwright.dev/python/docs/browsers#chromium
- …

fix(browser)!: default to Chromium channel for new headless mode

---

crawl4ai/async_crawler_strategy.py

Bug fix for long page screenshot.
**Error:**
The fixed `SCREENSHOT_HEIGHT_TRESHOLD` (default 10000) was too large, preventing scrolling for most pages. This resulted in only single viewport screenshots instead of full-page captures.
**Fix:**
Replaced the threshold check with a comparison of `scrollHeight` and `viewportHeight`. Scrolling now occurs when `scrollHeight` exceeds `viewportHeight`, ensuring full-page screenshots.

fix: not working long page screenshot

---

CODE_OF_CONDUCT.md
README.md

Code of conduct is adopted from [Contributor covenant](https://www.contributor-covenant.org/)

Docs: Add Code of Conduct for the community contributors

---

crawl4ai/html2text/__init__.py

This PR fixes the spacing issues in description lists (dl/dt/dd tags) while preserving anchor link handling and list functionality. The changes improve readability of scraped content by:
- Adding proper paragraph breaks between term-definition pairs
- Maintaining consistent indentation for definitions
- Using paragraph state counter for spacing control
Fixes #599 
- `/crawl4ai/crawl4ai/html2text/__init__.py`
- Updated description list tag handling to improve spacing and readability
- Added clarifying comments
- Preserved existing anchor and list functionality
- Tested with sample Blender documentation page
- Verified proper spacing between term-definition pairs
- Confirmed anchor links still work correctly
- Checked list formatting remains intact

Fix Markdown Incorrect Spacing #599

---

docs/md_v2/advanced/advanced-features.md

Added the missing "two spaces" to add a line break.
Otherwise, there is no new line in the existing version:
Fixes a small formatting bug, introduced by the commit: d09c611
I didn't create any issues as the bug was too small (and only for documentation).
I checked the "display the rich diff" view below and all looks good.

(Docs) Fix numbered list end-of-line formatting

---

docs/md_v2/extraction/llm-strategies.md

Please include a summary of the change and/or which issues are fixed.
Fixes link to LiteLLM project and spelling to match their branding
extraction/llm-strategies in the docs because that's where the issue was
Please describe the tests that you ran to verify your changes.
It's just a doc change
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] I have added/updated unit tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes

Fix LiteLLM branding and link

---

crawl4ai/async_crawler_strategy.py

Fixes #911
- `async_crawler_strategy.py`
- Use `querySelectorAll` to get all elements matching the selector.
- Use double quotes to wrap the selector, so the single quotes inside it won't cause problems. Keep the behavior consistent with the previous version.
Tested with following snippets, basically, it's the "Using css_selector" example, with the addition of `b[class='hnname']`.
```py
import asyncio
from crawl4ai import AsyncWebCrawler, CrawlerRunConfig
async def main():
config = CrawlerRunConfig(
css_selector="b[class='hnname'],.athing:nth-child(-n+30)"
)
async with AsyncWebCrawler() as crawler:
result = await crawler.arun(
url="https://news.ycombinator.com/newest", 
config=config
)
print("Partial HTML length:", len(result.cleaned_html))
print(result.cleaned_html)
if __name__ == …
```

fix(#911): css_selector is not working properly

---

crawl4ai/browser_manager.py

- fix default context page handling when there are no open pages
- `pytest -q --maxfail=1 -vv` *(fails: ModuleNotFoundError: No module named 'test_0')*

Fix use_managed_browser page creation

---

crawl4ai/async_webcrawler.py
crawl4ai/cli.py

Implements the missing `--deep-crawl` and `--max-pages` CLI options to enable deep crawling functionality from the command line. Also fixes the `'list' object has no attribute 'model_dump'` error that occurred during deep crawl result processing.
Fixes the GitHub issue where `crwl https://docs.crawl4ai.com --deep-crawl bfs --max-pages 3` was throwing "No such option: --deep-crawl" error. issue reference: #874 
- `crawl4ai/cli.py` - Added --deep-crawl and --max-pages CLI options with support for bfs/dfs/best-first strategies, updated result handling for both single and multiple crawl results
- `crawl4ai/async_webcrawler.py` - Fixed serialization error by adding type checking for media and links fields in aprocess_html function
- Verified CLI help shows new options correctly
- Tested deep …

Feature/CLI - deep-crawl: Add --deep-crawl CLI option with BFS/DFS/Best-First strategies and fix serialization error. ref #874

---

docs/md_v2/core/crawler-result.md

This PR updates the CrawlResult Documentation by adding missing fields:  fit_html, js_execution_result, redirected_url, network_requests, console_messages, tables.
[docs/md_v2/core/crawler-result.md](https://github.com/unclecode/crawl4ai/blob/develop/docs/md_v2/core/crawler-result.md) changed to update the documentation.
Verified and previewed the markdown file.

Update CrawlResult documentation with missing fields

---

docs/examples/docker_example.py
tests/docker_example.py

This PR does the following:
- Remove deprecated API token authentication from all Docker examples
- Fix async job endpoints: /crawl -> /crawl/job for submission, /task/{id} -> /crawl/job/{id} for polling
- Fix sync endpoint: /crawl_sync -> /crawl (synchronous)
- Remove non-existent /crawl_direct endpoint
- Update request format to use new structure with browser_config and crawler_config
- Fix response handling for both async and sync calls
- Update extraction strategy format to use proper nested structure
- Add Ollama connectivity check before running tests
- Update test schemas and selectors for current website structures
This makes the Docker examples work out-of-the-box with the current API structure.
Fixes (#1015 )
docs/examples/docker_example.py
tests/docker_example.py
Examples …

docs: remove CRAWL4AI_API_TOKEN references and use correct endpoints in Docker example scripts (#1015)

---

CHANGELOG.md
crawl4ai/async_configs.py
crawl4ai/async_webcrawler.py
crawl4ai/content_scraping_strategy.py
crawl4ai/utils.py
docs/md_v2/api/parameters.md
docs/md_v2/core/deep-crawling.md
tests/test_preserve_https_for_internal_links.py

Added a new `preserve_https_for_internal_links` configuration flag that preserves the original HTTPS scheme for same-domain links even when the server redirects to HTTP.
Fixes #1410
- Added `preserve_https_for_internal_links` flag to CrawlerRunConfig (default: False)  
- Updated URL normalization functions to support HTTPS preservation                
- Pass original URL scheme from async_webcrawler to content scraping strategy      
- Enhanced normalize_url to preserve HTTPS for same-domain links when flag is enabled  
- Added comprehensive test suite demonstrating the fix 
- When enabled: Internal links maintain HTTPS even after HTTP redirects            
- When disabled (default): Current behavior maintained (follows redirects)         
- Protocol-relative URLs (//example.com) respect …

feat: add preserve_https_for_internal_links flag to maintain HTTPS during crawling

---

deploy/docker/api.py
deploy/docker/server.py
tests/docker/test_server_requests.py

This PR does the following:
- Return comprehensive error messages along with status codes for api internal errors.
- Fix fit_html property serialization issue in both /crawl and /crawl/stream endpoints
- Add sanitization to ensure fit_html is always JSON-serializable (string or None)
- Add comprehensive error handling test suite.
Addresses #1335
`deploy/docker/api.py`: To fix fit_html causing serialization issue when scraping incorrect URL.
`deploy/docker/server.py`: To catch errors and exceptions in the api server.
`tests/test_server_request.py`: To add tests for error handling.
Ran docker tests and tested manually with correct and incorrect URLs.

Improve docker error handling

---

deploy/docker/c4ai-doc-context.md
pyproject.toml
setup.py

The library no longer supports Python 3.9 and so it was important to drop all references to python 3.9. 
- `pyproject.toml`: set requires-python to ">=3.10"; remove 3.9 classifier
- `setup.py`: set python_requires to ">=3.10"; remove 3.9 classifier
- `deploy/docker/c4ai-doc-context.md`: update python versions -> 3.10, 3.11, 3.12, 3.13
Built the package and tried installing with python 3.9 interpreter and python 3.10 interpreter.

Remove python 3.9 from supported versions and require Python >= 3.10

---

crawl4ai/deep_crawling/bff_strategy.py
tests/general/test_bff_scoring.py

Fixes #1253. Invert BestFirst priority (use negative scores) and remove pre-scoring link truncation; ensures highest-scoring URLs crawl first and all candidates are scored.
- crawl4ai/deep_crawling/bff_strategy.py – invert PQ scores, preserve original score in metadata, remove pre-scoring cap
- tests/general/test_bff_scoring.py – add unit test asserting crawl order by score and no premature truncation
Added unit test with dummy crawler/scorer; verifies order [u1, u4, u2] given scores 0.9, 0.7, 0.5 and max_pages=3

fix(deep-crawl): BestFirst priority inversion

---

deploy/docker/api.py

Fixes #1505 - Fixed `crawler_config` handling in streaming crawl requests to prevent overwriting user-provided configurations and added proper error handling for edge cases.
- api.py - Fixed line 475 where `crawler_config.scraping_strategy` was always being overwritten, added validation for configuration loading, URL processing, and proper error handling for streaming crawl requests.
- Tested streaming crawl with custom scraping strategies to ensure user configurations are preserved
- Tested with invalid configurations to verify error handling
- Tested with malformed URLs to ensure proper validation and fallback behavior
Similar code found with 1 license type

#1505 fix(api): update config handling to only set base config if not provided by user

---

crawl4ai/async_dispatcher.py
deploy/docker/api.py

* run_urls() returns None if an exception is raised, since we catch the exception but only log it
* The docker api then fails since we import json in the function (even though its already globally imported), which makes python believe it's a local variable, causing an UnboundLocalError
* api.py - Remove unneeded local import causing UnboundLocalError
* async_dispatcher.py - return the result list in the finally block so that we respect the function signature and not try to unpack None in arun_many
Please describe the tests that you ran to verify your changes.

Fix: run_urls() returns None, crashing arun_many()
